name: Huawei EVS Create Snapshot - PROD

on:
  workflow_dispatch:

env:
  PROJECT_ID: "da9c89f493fb4554afab5f67a07ba4fd"
  REGION: "tr-west-1"
  DATA_VOLUME_ID: "1e094019-0512-448d-be9b-9d5162f3067c"
  SNAPSHOT_NAME: "levy-snapshot"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Huawei Cloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          curl -LO "https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/huaweicloud-cli-linux-amd64.tar.gz"
          tar -zxvf huaweicloud-cli-linux-amd64.tar.gz
          sudo mv $(pwd)/hcloud /usr/local/bin/
          yes y | hcloud auto-complete on
          hcloud version

      - name: Configure Huawei Cloud CLI profile
        run: |
          hcloud configure set --cli-access-key=${{ secrets.HUAWEI_PLATFORM_OPERATIONS_ACCESS_KEY_ID_BINBIN_PROD }} --cli-secret-key=${{ secrets.HUAWEI_PLATFORM_OPERATIONS_SECRET_KEY_BINBIN_PROD }} --cli-region=${{ env.REGION }}

      - name: Print Environment Variables (Debugging)
        run: |
          echo "REGION: ${{ env.REGION }}"
          echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
          echo "DATA_VOLUME_ID: ${{ env.DATA_VOLUME_ID }}"
          echo "SNAPSHOT_NAME: ${{ env.SNAPSHOT_NAME }}"

      - name: Create EVS Snapshot
        id: create-snapshot
        run: |
          yes y | sudo hcloud EVS CinderCreateSnapshot \
            --cli-region="${{ env.REGION }}" \
            --project_id="${{ env.PROJECT_ID }}" \
            --cli-access-key="${{ secrets.HUAWEI_PLATFORM_OPERATIONS_ACCESS_KEY_ID_BINBIN_PROD }}" \
            --cli-secret-key="${{ secrets.HUAWEI_PLATFORM_OPERATIONS_SECRET_KEY_BINBIN_PROD }}" \
            --snapshot.volume_id="${{ env.DATA_VOLUME_ID }}" \
            --snapshot.name="${{ env.SNAPSHOT_NAME }}" \
            --debug
