name: Huawei EVS Create Snapshot - PROD

on:
  workflow_dispatch:

env:
  PROJECT_ID: "da9c89f493fb4554afab5f67a07ba4fd"
  REGION: "tr-west-1"
  DATA_VOLUME_ID: "1e094019-0512-448d-be9b-9d5162f3067c"
  SNAPSHOT_NAME: "levy-snapshot"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install or Update Huawei Cloud KooCLI
        id: install-koocli
        run: |
          sudo curl -sSL https://eu-west-101-apiexplorer-cli.obs.eu-west-101.myhuaweicloud.eu/cli/latest/hcloud_install.sh -o ./hcloud_install.sh
          yes y | sudo bash ./hcloud_install.sh -y
          yes y | sudo hcloud update || echo "KooCLI is already up-to-date."

      - name: Create EVS Snapshot
      id: create-snapshot
      run: |
        yes y | sudo hcloud EVS CinderCreateSnapshot \
          --cli-region="${{ env.REGION }}" \
          --project_id="${{ env.PROJECT_ID }}" \
          --cli-access-key="${{ secrets.HUAWEI_PLATFORM_OPERATIONS_ACCESS_KEY_ID_BINBIN_PROD }}" \
          --cli-secret-key="${{ secrets.HUAWEI_PLATFORM_OPERATIONS_SECRET_KEY_BINBIN_PROD }}" \
          --snapshot.volume_id="${{ env.DATA_VOLUME_ID }}" \
          --snapshot.name="${{ env.SNAPSHOT_NAME }}" \
          --debug

